export const Constance = {
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_CLOSE: 'MODAL_CLOSE',
  LOGIN_USER: 'LOGIN_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER'
}